Class BusinessAnalysis.Interop.Production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="BusinessAnalysis.Interop.Production" LogGeneralTraceEvents="false">
  <Item Name="BS_InboundFile" ClassName="BusinessAnalysis.Interop.BS.InboundFile" Category="" PoolSize="1" Enabled="true" Foreground="false"/>
  <Item Name="BO_AnalyzeFile" ClassName="BusinessAnalysis.Interop.BO.AnalyzeFile" Category="" PoolSize="1" Enabled="true" Foreground="false"/>
</Production>
}

}
